             .BSS 

;---------------------------------------------------------------
; segment overlay
;

souri_5::    .DS.b 16
souri_7::    .DS.b 16
souri_8::    .DS.b 16
souri_11::   .DS.b 16
rnd::        .DS.b 16
cd003::      .DS.b 16
sys01::      .DS.b 16
ecrswap::    .DS.b 16
souri_13::   .DS.b 16
sys00::      .DS.b 16
puttcx::     .DS.b 16
pbox::       .DS.b 16

cd009::      
text::       .DS.b 16
adrdicour::  .DS.b 16
degraon::    .DS.b 16
degraoff::   .DS.b 16
palettechidam::        .DS.b 16
souri_18::   .DS.b 16
bsour::      .DS.b 16
adrbsour::   .DS.b 16
contvbl::    .DS.b 16
souri_10::   .DS.b 16
polyl_1::    .DS.b 16
polyl_2::    .DS.b 16
polyl_4::    .DS.b 16
polyl::      .DS.b 16
ad_seq::     .DS.b 16
novoie::     .DS.b 16
play_seq::   .DS.b 16
table_sons:: .DS.b 16
seq_silence::          .DS.b 16
adrbiicour:: .DS.b 16
polyl_5::    .DS.b 16
polyl_6::    .DS.b 16
box::        .DS.b 16
puttc_1::    .DS.b 16
puttc_2::    .DS.b 16
puttc_3::    .DS.b 16
puttc_4::    .DS.b 16
objstruc::   .DS.b 16
evi::        .DS.b 16
objtypedata::          .DS.b 16



















